### ISSUE TITLE
Hi Sorry , i was sick ,  i connect to relay server how to disable de SMTP_AUTH . I can reach the server now, but a i need to disable authentication.

### ISSUE THREAD

**Issue by marting885** [bmarsh9/gapps#101]
Hi Sorry , i was sick ,  i connect to relay server how to disable de SMTP_AUTH . I can reach the server now, but a i need to disable authentication. 

Thanks

_Originally posted by @marting885 in https://github.com/bmarsh9/gapps/issues/98#issuecomment-1779198691_

**Comment by bmarsh9** [comment]
Sorry, thats not something we support at this time.
