### ISSUE TITLE
Error when saving evidence

### ISSUE THREAD

**Issue by bmarsh9** [bmarsh9/gapps#102]
#### python3 manage.py shell

`app.config["EVIDENCE_FOLDER"]` is equal to `/app/app/files/evidence` by default within docker. It should be `/app/files/evidence`

**Comment by Jamesw151619** [comment]
Not sure if this is related, i cannot create evidence while inside of a control on a project. seems like the button isnt making the call, i don't get any error messages. (did not debug)

**Comment by bmarsh9** [comment]
Its related - now fixed @Jamesw151619
