### ISSUE TITLE
Add the ASD Essential 8

### ISSUE THREAD

**Issue by Matt-Thom** [bmarsh9/gapps#105]
Add the relevant information to the system to allow users to create a project to assess a tenants compliance to the ASD Essential 8 found at the following URL
[Essential Eight](https://www.cyber.gov.au/resources-business-and-government/essential-cyber-security/essential-eight)

**Comment by bmarsh9** [comment]
@Matt-Thom you can add new frameworks here: https://github.com/bmarsh9/gapps#loading-new-frameworks-into-gapps
