### ISSUE TITLE
Issue with Email Apps Like Outlook , Zoho

### ISSUE THREAD

**Issue by S-Velayutham** [bmarsh9/gapps#109]
Just want to start by saying thank you for this wonderful project. I signed to the sas based GAPPS and works fine inviting members but we are using office 365 where tried methods with yaml but still couldnt get it to work. 
Checked Gapps mx records are it was usingg google. where as ur org uses microsoft 365 :(

Finally managed to send it however mails arent receiving inspite of lowering our security setting and checking junk. 
If you could provide us a step step . i would be really helpful. 

Thanks

**Comment by bmarsh9** [comment]
@S-Velayutham Could you edit the `CHANGE ME` values below, save/run the script and then visit `localhost:5000/` in your browser? This will help test. You can also set the env variable MAIL_DEBUG=True to show more logs

```
from flask import Flask
from flask_mail import Mail, Message

app = Flask(__name__)
mail = Mail(app)

@app.route("/")
def index():
    msg = Message("Hello",
                  sender="CHANGE ME",
                  recipients=["CHANGE ME"])
```

**Comment by bmarsh9** [comment]
Closing - reopen if you have the same issue
