### ISSUE TITLE
Building and pushing

### ISSUE THREAD

**Issue by tssingtampa** [bmarsh9/gapps#111]
docker build -t gapps:3.4.3 .
docker tag gapps:3.4.3 bmarsh13/gapps:3.4.3
docker push bmarsh13/gapps:3.4.3

I would like to integrate a framework into my project, but I am encountering difficulties while following the previous documentation provided by the repository itself. Could you please guide me through the necessary steps to successfully implement it? I appreciate your assistance in advance. Best regards.

**Comment by bmarsh9** [comment]
@tssingtampa Are you trying to add a new (custom) framework to the tool? The docker commands you listed are just building and pushing a new image to docker hub

**Comment by tssingtampa** [comment]
Below I attach an image of my issue. I'm sure I'll do something wrong, if you can help me with that, I'll thank you in advance.

![image](https://github.com/bmarsh9/gapps/assets/142441903/7d56d23e-7441-4a7d-897b-aa5176257e6d)


> @tssingtampa Are you trying to add a new (custom) framework to the tool? The docker commands you listed are just building and pushing a new image to docker hub

**Comment by bmarsh9** [comment]
@tssingtampa Yeah you are trying to push a new image to my dockerhub repository (which you don't have access to). Could you explain what you are trying to accomplish and I may be able to point you in the right direction?

**Comment by tssingtampa** [comment]
ok, I am trying to add a custom framework following the steps described in the section Loading new frameworks into Gapps, I have put the .json in the app/files/base_controls/ folder. Additionally, I only comment that I have not changed other than the email sender configuration and it has worked well. So I would like if you guide me please, I would like to do tests with the json that I have put in the folder.

**Comment by bmarsh9** [comment]
@tssingtampa  Just build the image: `docker build -t custom-gapps .`

Then change the image reference in the docker-compose file. Lastly restart the images `docker-compose up -d`

**Comment by tssingtampa** [comment]
Thank you very much for that, I will be following the steps, thank you for your time.

**Comment by tssingtampa** [comment]
Good afternoon, doing the following steps has worked for me.

docker rmi custom-gapps
docker build -t custom-gapps .

nano docker-compose.yml
##image: bmarsh13/gapps:3.5.3, change it to image: custom-gapps

docker-compose up -d

Before asking you some things, I must tell you that the PC turned off and when it came back the tenant was still there but the frameworks were not there, this has happened about 3 times, therefore my projects were not there either, this happened with the original image of your project without using the custom one. Another thing I wanted to ask you is how I can expand the development of your project, I would like to know if it is possible. I would also like to know in what language it is created. my best cordial greetings to you.
