### ISSUE TITLE
Problem when turning off the pc, the information was deleted.

### ISSUE THREAD

**Issue by tssingtampa** [bmarsh9/gapps#113]
Before asking you some things, I must tell you that the PC turned off and when it came back the tenant was still there but the frameworks were not there, this has happened about 3 times, therefore my projects were not there either, this happened with the original image of your project without using the custom one. Another thing I wanted to ask you is how I can expand the development of your project, I would like to know if it is possible. I would also like to know in what language it is created. my best cordial greetings to you.

It is worth mentioning that I have not restarted docker, it starts by itself.

**Comment by bmarsh9** [comment]
Take a look at persisting data in docker: https://stackoverflow.com/questions/41637505/how-to-persist-data-in-a-dockerized-postgres-database-using-volumes

Closing as this isn’t a Gapps issue, but a docker one
