### ISSUE TITLE
NGINX Reverse Proxy

### ISSUE THREAD

**Issue by rmsferreira** [bmarsh9/gapps#126]
Dear all.

I'm trying to reverse proxy GAPPS with nginx, however I'm facing some issues.

Can someone tell me how can I proxy http://IP:5000 to something like https://gapps.domain.com

This is my actual configuration:

map $http_upgrade $connection_upgrade {
    default upgrade;
    '' close;
}
server {
    listen 80;
    listen [::]:80;
    server_name XXXX.domain.com;
    return 307 https://$server_name$request_uri;
}
server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name XXXX.domain.com;
    ssl_certificate /etc/nginx/ssl/origin.pem;
    ssl_certificate_key /etc/nginx/ssl/origin.key;
    location / {
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        client_max_body_size 1000m;
        proxy_redirect off;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://IP:5000;
    }
}

Thanks.

**Comment by bmarsh9** [comment]
Sorry this isn’t a Gapps issue. But you can try this resource: https://www.digitalocean.com/community/tutorials/how-to-configure-nginx-as-a-reverse-proxy-on-ubuntu-22-04
