### ISSUE TITLE
NIST Framework view controls errors

### ISSUE THREAD

**Issue by rmsferreira** [bmarsh9/gapps#129]
Dear all I'm facing some error when try to use NIST 800 Framework.

After create a project using NIST 800 Framework everything is ok, but when I try to  go to controls a stuck on read and I receive the following error:

172.29.0.3 - - [05/Jun/2024:10:27:35 +0000] "GET /api/v1/projects/1?review-summary=true HTTP/1.1" 200 645 "https://xxxxxxxxx.xxxxxx.xxx/projects/1" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36"
[2024-06-05 10:28:37 +0000] [42] [CRITICAL] WORKER TIMEOUT (pid:46)
/app/app/models.py:1803: UserWarning: The 'sha256' password method is deprecated and will be removed in Werkzeug 2.4. Migrate to the 'scrypt' method.
  return check_password_hash(self.password, password)
[2024-06-05 10:28:37 +0000] [46] [INFO] Worker exiting (pid: 46)
[2024-06-05 10:28:37 +0000] [142] [INFO] Booting worker with pid: 142

Other framework as ISO or SOC2 I don't facing this problem.

**Comment by rmsferreira** [comment]
I manage this by modifying the run.sh and add --timeout=60 --keep-alive 60, so now  the worker don't have timeout.

So can you please change and add the possibility to specify this in environment variables.

Thanks.

**Comment by ieee13961394** [comment]
Just throwing my two pennies in here: 

I have the same issue at the OP.  Sits there trying to load and never does, all the other frameworks work.

**Comment by bmarsh9** [comment]
So I think the issue is its just the largest framework, by far. There are plenty of things to optimize on the backend to speed things up. But increasing the worker timeouts in Gunicorn is probably the best answer right now as @rmsferreira suggested. 

Ill add that as ENV variables

**Comment by bmarsh9** [comment]
Done - you can control it with these two env variables:

```
GUNICORN_TIMEOUT
GUNICORN_KEEP_ALIVE
```
