### ISSUE TITLE
Implementation levels

### ISSUE THREAD

**Issue by Vijayragha1** [bmarsh9/gapps#16]
Instead of percentage wouldn't it better to add not implemented - partially implemented - implemented. 🤔🤔 or am i missing something?

**Comment by bmarsh9** [comment]
Are you talking about the progress bar displaying how much of the control is implemented?

**Comment by Vijayragha1** [comment]
yep

**Comment by bmarsh9** [comment]
This is more of a UI thing. Internally, the percentage maps to partially, mostly implemented, fully implemented. See the screenshot below where the percentage is at 75% and the label is "Mostly Implemented". This was mostly done to make it easier if one framework had 3 levels of implementation (such as SOC2) and another framework used more/less. 

<img width="623" alt="c10" src="https://user-images.githubusercontent.com/26391921/210909058-ce12242e-0aee-41b0-9ea4-9dd928eda6c7.PNG">

**Comment by Vijayragha1** [comment]
Ahh i see.
