### ISSUE TITLE
Considerations for the name

### ISSUE THREAD

**Issue by SupaChop** [bmarsh9/gapps#18]
I think it may be beneficial to rethink the name of this application. "Gapps" as a moniker is already used for the android google apps suite (See xda developers) as well some professional organizations. Additionally, (to me at least) doesn't indicate what the application does exactly. Perhaps at some point consider a more unique and telling name for the application. ChatGPT could potentially be useful here.

**Comment by Vijayragha1** [comment]
ah yes, my friend pointed out the same when i showed him this.

**Comment by bmarsh9** [comment]
Yeah I think I will end up changing it before the next large release - thanks
