### ISSUE TITLE
Add document storage and linking to controls

### ISSUE THREAD

**Issue by SupaChop** [bmarsh9/gapps#2]
Add a document management/storage system with the ability to link documents to specific controls as evidence. Ideally with markup capabilities so assessors can reference the documents within the application without leaving it.

**Comment by bmarsh9** [comment]
@SupaChop This is a good suggestion. If I understand correctly and from a user perspective, you would navigate to the "Evidence page". Inside that page, you can upload evidence there and link it to multiple controls within a project. 

Currently you can upload evidence to each control but there isn't a view that shows "all evidence mapped to each control".

**Comment by bmarsh9** [comment]
Addressed in https://github.com/bmarsh9/gapps/pull/11
