### ISSUE TITLE
Expanding menubar

### ISSUE THREAD

**Issue by Vijayragha1** [bmarsh9/gapps#22]
Is there a way to make the menu bar on left expand when mouse is hovered over it or maybe by a click of button?

**Comment by bmarsh9** [comment]
@Vijayragha1 I think this will suffice for now - on hover with mouse, shows the label

![hover](https://user-images.githubusercontent.com/26391921/214636296-6a69b4d8-bd02-4a70-abb3-2ef493c245c2.PNG)

**Comment by Vijayragha1** [comment]
Great.
