### ISSUE TITLE
Add kanban style board for managing re-occurring tasks

### ISSUE THREAD

**Issue by bmarsh9** [bmarsh9/gapps#3]
Some tasks (such as in SOC2) require tasks to be completed on a interval. Ideally we have a kanban [style board such as this ](https://js.devexpress.com/Demos/WidgetsGallery/Demo/Sortable/Kanban/jQuery/Light/) that allows you to view tasks and receive notifications. Or a integration with Gitlab/Github

**Comment by PekkaJalonen** [comment]
Having integration to Jira to create issues would be great for tasks to be completed.

**Comment by bmarsh9** [comment]
Not on roadmap.
