### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by fabianhjr** [bmarsh9/gapps#4]
Hi just a heads up on licensing, from the Creative Commons FAQ: [https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software](https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software)

> We recommend against using Creative Commons licenses for software. Instead, we strongly encourage you to use one of the very good software licenses which are already available. We recommend considering licenses listed as free by the Free Software Foundation and listed as “open source” by the Open Source Initiative.  
>  
> Unlike software-specific licenses, CC licenses do not contain specific terms about the distribution of source code, which is often important to ensuring the free reuse and modifiability of software. Many software licenses also address patent rights, which are important to software but may not be applicable to other copyrightable works.  
>  
> Additionally, our licenses are currently not compatible with the major software licenses, so it would be difficult to integrate CC-licensed work with other free software. Existing software licenses were designed specifically for use with software and offer a similar set of rights to the Creative Commons licenses.

Since you chose CC-BY-NC-ND license you should probably stick with "source available"  software licenses or something like [Prosperity Public License](https://prosperitylicense.com/) (A non-commercial software license), [Business Source License](https://mariadb.com/bsl-faq-adopting/) (Recently adopted by LightBend / Akka and other big projects), or [Fair Source License](https://fair.io)

There are also some Copy-far-left or Copyfair Licenses that could be appealing to you as similar to CC-BY-NC-ND: [https://github.com/LibreCybernetics/awesome-copyfarleft](https://github.com/LibreCybernetics/awesome-copyfarleft)

**Comment by bmarsh9** [comment]
Thanks!
