### ISSUE TITLE
Create Projects with CMMC levels

### ISSUE THREAD

**Issue by XPERTPCNET** [bmarsh9/gapps#44]
Can't create CMMC projects levels 1-3 since currently a CMMC project has all the controls 238 controls. Would like to be able to create a CMMC 2.0 Level 1 project with 17 controls.

**Comment by XPERTPCNET** [comment]
This was quickly resolved and now CMMC level selection is active. 
![image](https://user-images.githubusercontent.com/1085086/228290001-5c6acac2-8614-443c-9b64-fc724c7990a8.png)

**Comment by bmarsh9** [comment]
CMMC v2 implemented within 3.3.2
