### ISSUE TITLE
Should have a variable, MAIL_AUTH (True|False) saying that there is no need to authenticate against the MTA.

### ISSUE THREAD

**Issue by dblas** [bmarsh9/gapps#50]
Excellent! Bravo.
Carry on!

MAIL_USERNAME & MAIL_PASSWORD MUST exist says the product.
BUT I don't need to id/auth agains my mail MTA since the mail MTA is in the same Docker that all the products.
You SHOULD have a variable, MAIL_AUTH (True|False) saying that there is no need to authenticate against the MTA.
Meanwhile impossible to invite someone.

db

**Comment by bmarsh9** [comment]
You can invite people to the platform without email, you just have to share the invite link with the user after adding them

**Comment by bmarsh9** [comment]
Closing

**Comment by dblas** [comment]
> You can invite people to the platform without email, you just have to share the invite link with the user after adding them

ok, thanks.
Bravo (again).
db
