### ISSUE TITLE
Improve: Add Security Policy

### ISSUE THREAD

**Issue by manuel-sommer** [bmarsh9/gapps#53]
Hi all,

I found a vulnerability and I would like to report it to improve the security of gapps. Could you please add a Security.md to enable collaborators to report vulnerabilities.

**Comment by manuel-sommer** [comment]
https://github.com/bmarsh9/gapps/pull/54

**Comment by bmarsh9** [comment]
@manuel-sommer Added. Feel free to describe the vulnerabilities in this thread or a new issue
