### ISSUE TITLE
Add ability to directly upload/host evidence within the project

### ISSUE THREAD

**Issue by SupaChop** [bmarsh9/gapps#6]
The ability to add evidence directly to the control would increase the usability of the app and it convenience, leaving the app to view the evidence becomes cumbersome when done many times throughout the project. 
![Evidence](https://user-images.githubusercontent.com/118844734/203427057-ea7ca75b-a191-40a4-815c-c0c19aa3befb.PNG)

**Comment by bmarsh9** [comment]
Agreed - I think this could be tied in with https://github.com/bmarsh9/gapps/issues/2

**Comment by bmarsh9** [comment]
Addressed in https://github.com/bmarsh9/gapps/pull/11
