### ISSUE TITLE
Consider buttons for each function vs Elipsis when possible

### ISSUE THREAD

**Issue by SupaChop** [bmarsh9/gapps#8]
The use of ellipses as opposed to buttons causes the available functionality to not be immediately clear. The use of simple buttons for each function is more user friendly and allows the user to immediately understand what the available options are. (Not super important) 
![Elipsis](https://user-images.githubusercontent.com/118844734/203427756-31685eb4-77e2-44c3-bd76-7ba2ba7c91ef.PNG)

**Comment by bmarsh9** [comment]
Fixed with the new UI
